# bomedb-vocalballsbot-vapronva
version: "3"

services:
  bot:
    image: registry.vapronva.pw/vapronva/vocal_balls_bot-tg_bot/bot:latest
    container_name: "worker-vocalballsbot-vapronva-main"
    restart: unless-stopped
    environment:
      VOSK_API_KEY: ${VOSK_API_KEY}
      VOSK_ENDPOINT_ENGLISH: ${VOSK_ENDPOINT_ENGLISH}
      VOSK_ENDPOINT_RUSSIAN: ${VOSK_ENDPOINT_RUSSIAN}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN_STAGING}
      TELEGRAM_BOT_WORKERS: ${TELEGRAM_BOT_WORKERS}
      VPRW_RCPAPI_ENDPOINT: ${VPRW_RCPAPI_ENDPOINT}
      VPRW_RCPAPI_KEY: ${VPRW_RCPAPI_KEY}
      APPWRITE_API_ENDPOINT: ${APPWRITE_API_ENDPOINT}
      APPWRITE_PROJECT_ID: ${APPWRITE_PROJECT_ID}
      APPWRITE_API_KEY: ${APPWRITE_API_KEY}
      APPWRITE_STORAGE_BOTAVATAR: ${APPWRITE_STORAGE_BOTAVATAR}
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "3"

networks:
  default:
    driver: bridge
    name: "bomedb-vocalballsbot-vapronva-network"
    ipam:
      driver: default
      config:
        - subnet: 172.16.80.0/24
          gateway: 172.16.80.1
